---
title: "MPDW"
author: "Johannes Pande Manurung"
date: "2024-11-01"
output: rmdformats::readthedown
---


Rata-rata lama penyinaran matahari kalimantan barat stasiun Oesman 1 Januari 2011 - 31 Oktober 2024

```{r}
library(ggplot2)
library(tsibble)
library(tseries)
library(MASS)
library(forecast)
library(TSA)
library(TTR)
library(aTSA)
library(graphics)
library(readxl)
library(xts)
library(rmdformats)
```

## Data SM Oesman 
```{r}
dt.oesman <- read_xlsx("C:/Users/Asus/Documents/IPB/Semester 5/MPDW/Rata2 SS Stasiun (1).xlsx", sheet=4)
dt.oesman
```

```{r}
dt.oesman.ts <- ts(dt.oesman$mean_ss)
```

```{r}
ts.plot(dt.oesman.ts, xlab="Periode Waktu", ylab="SS", main = "Plot Data Deret Waktu")
points(dt.oesman.ts)
```
## Pembagian Data
```{r}
datatrain <-dt.oesman[1:565,]
datatest <- dt.oesman[566:nrow(dt.oesman),]

train.ts <- ts(datatrain$mean_ss)
test.ts <- ts(datatest$mean_ss)
```

```{r}
plot(train.ts, col="blue",main="Plot data latih")
points(train.ts)
```

```{r}
plot(test.ts, col="red",main="Plot data uji")
points(test.ts)
```


```{r}
class(train.ts)
```
```{r}
is.numeric(train.ts)
```


## Uji Kestasioneran dalam Rataan
```{r}
acf(train.ts)
```

```{r, warning=FALSE}
tseries::adf.test(train.ts)
```
## Uji Kestasioneran dalam Ragam
```{r}
index <- seq(1:565)
bc = boxcox((train.ts+0.1)~index, lambda = seq(-1,2,by=0.01))
```
## Plot PACF, ACF, dan EACF

```{r}
pacf(train.ts)
```
```{r}
acf(train.ts)
```


```{r}
eacf(train.ts)
```
## ARIMA (1,0,1)

```{r}
model101<- Arima(train.ts, order=c(1,0,1),method="ML")
summary(model101)
lmtest::coeftest(model101)
```

## ARIMA (1,0,0)

```{r}
model100<- Arima(train.ts, order=c(1,0,0),method="ML")
summary(model100)
lmtest::coeftest(model100)
```

## ARIMA (2,0,0)

```{r}
model200<- Arima(train.ts, order=c(2,0,0),method="ML")
summary(model200)
lmtest::coeftest(model200)
```

## ARIMA (0,0,7)

```{r}
model007<- Arima(train.ts, order=c(0,0,7),method="ML")
summary(model007)
lmtest::coeftest(model007)
```

## ARIMA (2,0,2)

```{r}
model202<- Arima(train.ts, order=c(2,0,2),method="ML")
summary(model202)
lmtest::coeftest(model202)
```

## Uji Asumsi Model Tentatif ARIMA (1,0,1)

```{r}
sisaan.101 <- model101$residuals 
par(mfrow=c(2,2)) 
qqnorm(sisaan.101) 
qqline(sisaan.101, col = "blue", lwd = 2) 
plot(c(1:length(sisaan.101)),sisaan.101) 
acf(sisaan.101) 
pacf(sisaan.101) 
```


```{r}
# Asumsi Normalitas Sisaan
nortest::ad.test(sisaan.101)
```

```{r}
# Asumsi Sisaan Saling Bebas
Box.test(sisaan.101, type = "Ljung")
```

```{r}
# Asumsi Ragam Sisaan Homogen
Box.test((sisaan.101)^2, type = "Ljung")
```

```{r}
# Asumsi Nilai Tengah Sisaan sama dengan Nol
t.test(sisaan.101, mu = 0, conf.level = 0.95)
```

## Overfitting ARIMA(1,0,1)

### ARIMA(1,0,2)
```{r}
model102 <- Arima(train.ts, order=c(1,0,2),method="ML")
summary(model102)
```
```{r}
lmtest::coeftest(model102)
```

### ARIMA(2,0,1)
```{r}
model201 <- Arima(train.ts, order=c(2,0,1),method="ML")
summary(model201)
```
```{r}
lmtest::coeftest(model201)
```



## Forecasting

```{r}
length(test.ts)
```

```{r}
#---FORECAST---#
ramalan.da <- forecast::forecast(model101, h = (158+24)) 
ramalan.da
data.ramalan.da <- ramalan.da$mean
plot(ramalan.da)

```
```{r}
hasil<- data.ramalan.da
ts.plot(train.ts,hasil)
```



```{r}
perbandingan.da<-matrix(data=c(test.ts, hasil[1:158]),
                     nrow = 158, ncol = 2)
colnames(perbandingan.da)<-c("Aktual","Hasil Forecast")
perbandingan.da
accuracy(ts(hasil[1:158]), test.ts)
```

```{r}
accuracy(ts(hasil[1:158]), test.ts)
```
```{r}
mape <- mean(abs((perbandingan.da[,1] - perbandingan.da[,2]) / perbandingan.da[,1])) * 100
mape
```
```{r}
rmse <- sqrt(mean((perbandingan.da[,1] - perbandingan.da[,2])^2))
rmse
```
```{r}
hasil[159:(158+24)]
```

```{r}
plot(model101$fitted)
```
```{r}
mean(abs((train.ts - model101$fitted)/train.ts))*100
```
```{r}
arima_tr <- data.frame(train.ts, model101$fitted)
arima_tr
```


```{r}
arima_test <- data.frame(test.ts, hasil[1:158])
arima_test
```
